CREATE TABLE clientes
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome          VARCHAR(255),
    email         VARCHAR(255),
    telefone      VARCHAR(255),
    endereco      VARCHAR(255),
    data_cadastro TIMESTAMP,
    ativo         BOOLEAN,
    CONSTRAINT pk_clientes PRIMARY KEY (id)
);